In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [16]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [17]:
df =pd.read_csv(r"C:\Users\ADMIN\Downloads\product_data.csv")

In [18]:
df.head()

   Product ID Product Name  Price  Stock Product Category  Encoded Category
0         101       Laptop   1000     50      Electronics                 0
1         102        Shirt     50    200         Clothing                 1
2         103          NaN    300     30        Furniture                 2
3         104        Phone    800    100      Electronics                 0
4         105        Pants     60    150         Clothing                 1

In [19]:
df.isnull()

   Product ID  Product Name  Price  Stock  Product Category  Encoded Category
0       False         False  False  False             False             False
1       False         False  False  False             False             False
2       False          True  False  False             False             False
3       False         False  False  False             False             False
4       False         False  False  False             False             False
5       False          True  False  False             False             False
6       False         False  False  False             False             False
7       False          True  False  False             False             False
8       False         False  False  False             False             False
9       False         False  False  False             False             False

In [20]:
df.isnull().sum()

Product ID          0
Product Name        3
Price               0
Stock               0
Product Category    0
Encoded Category    0
dtype: int64

In [21]:
df.isnull().sum().sum()

np.int64(3)

In [22]:
df.dropna()

   Product ID Product Name  Price  Stock Product Category  Encoded Category
0         101       Laptop   1000     50      Electronics                 0
1         102        Shirt     50    200         Clothing                 1
3         104        Phone    800    100      Electronics                 0
4         105        Pants     60    150         Clothing                 1
6         107       Jacket    100    150         Clothing                 1
8         109   Smartwatch    250    120      Electronics                 0
9         110      Sweater     80    200         Clothing                 1

In [23]:
df.dropna(axis=1)

   Product ID  Price  Stock Product Category  Encoded Category
0         101   1000     50      Electronics                 0
1         102     50    200         Clothing                 1
2         103    300     30        Furniture                 2
3         104    800    100      Electronics                 0
4         105     60    150         Clothing                 1
5         106    400     60      Electronics                 0
6         107    100    150         Clothing                 1
7         108    150     70        Furniture                 2
8         109    250    120      Electronics                 0
9         110     80    200         Clothing                 1

In [26]:
Label_Encoder = LabelEncoder()
df["Product Category"] = Label_Encoder.fit_transform(df["Product Category"])
df

   Product ID Product Name  Price  Stock  Product Category  Encoded Category
0         101       Laptop   1000     50                 1                 0
1         102        Shirt     50    200                 0                 1
2         103          NaN    300     30                 2                 2
3         104        Phone    800    100                 1                 0
4         105        Pants     60    150                 0                 1
5         106          NaN    400     60                 1                 0
6         107       Jacket    100    150                 0                 1
7         108          NaN    150     70                 2                 2
8         109   Smartwatch    250    120                 1                 0
9         110      Sweater     80    200                 0                 1

In [25]:
df["Product Category"]

0    1
1    0
2    2
3    1
4    0
5    1
6    0
7    2
8    1
9    0
Name: Product Category, dtype: int64

In [31]:
df_new = df.drop(columns=["Product Category"])
df_new

   Product ID Product Name  Price  Stock  Encoded Category
0         101       Laptop   1000     50                 0
1         102        Shirt     50    200                 1
2         103          NaN    300     30                 2
3         104        Phone    800    100                 0
4         105        Pants     60    150                 1
5         106          NaN    400     60                 0
6         107       Jacket    100    150                 1
7         108          NaN    150     70                 2
8         109   Smartwatch    250    120                 0
9         110      Sweater     80    200                 1

In [32]:
df["Product Category"].values.reshape(-1, 1)

array([[1],
       [0],
       [2],
       [1],
       [0],
       [1],
       [0],
       [2],
       [1],
       [0]])

In [33]:
df['Product Category'].values.reshape(-1, 1).ndim

2

In [37]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(df['Product Category'].values.reshape(-1, 1)).toarray()
X

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [40]:
get_dummies_product_data = pd.get_dummies(df_new)

get_dummies_product_data.head()

,Product ID,Price,Stock,Encoded Category,Product Name_Jacket,Product Name_Laptop,Product Name_Pants,Product Name_Phone,Product Name_Shirt,Product Name_Smartwatch,Product Name_Sweater
0,101,1000,50,0,False,True,False,False,False,False,False
1,102,50,200,1,False,False,False,False,True,False,False
2,103,300,30,2,False,False,False,False,False,False,False
3,104,800,100,0,False,False,False,True,False,False,False
4,105,60,150,1,False,False,True,False,False,False,False